### ISSUE TITLE
/audit returning 403

### ISSUE THREAD

**Issue by DarthHater** [salesforce/salesforce-cla#14]
Ok I sorta got this up and running, but now I'm consistently getting a 403 on `/audit`

The exception is:

```
play.api.UnexpectedException: Unexpected exception[IncorrectResponseStatus: Expected status code 200 but got 403 - You do not have access to organization memberships.]
```

This is puzzling to me, as I'm setting this up for @sonatype-nexus-community , and I'm an admin of that Org. I can imagine maybe something is wonky somewhere though as I had to create a GitHub app, and there's no reference of a slug, etc... anywhere (pulling at straws here). 

A screenshot of the OAuth:

![screen shot 2018-02-16 at 11 45 56 am](https://user-images.githubusercontent.com/5544326/36328566-0b95b282-130f-11e8-9f9f-40fe36edc30e.png)

I can try and debug this myself, but was wondering if there was a quick answer.

**Comment by jamesward** [comment]
For some reason it is using the wrong scope.  Looking into this.

**Comment by DarthHater** [comment]
Word up! I'm learning Scala by the second, so I surmise you'll beat me.

**Comment by DarthHater** [comment]
Ok, I finally got SBT debugging in IDEA, and your suspicion is confirmed, the access token I get back does not have access to read:org. I went ahead and generated one for my account that did and the call works fine, so there's something odd going on in the code. If I can figure it out I'll send you a PR.
